### ISSUE TITLE
Cannot stop advertising

### ISSUE THREAD

**Issue by ot-repo** [Erhannis/flutter_zeroconnect#1]
Hello,

after I start advertising, I cannot stop it anymore.

```
var server = ZeroConnect(localId: serverId);
await server.advertise(
  serviceId: "SYNCSERVICE",
  callback: (messageSock, nodeId, serviceId) async {},
);

var client = ZeroConnect(localId: clientId);
var availableServices = await client.scan(serviceId: "SYNCSERVICE", time: Duration(seconds: 5));

//availableServices includes 1 Ad as expected.

await server.close(); // not working
availableServices = await client.scan(serviceId: "SYNCSERVICE", time: Duration(seconds: 5));

//availableServices still includes 1 Ad!.
```

Any idea what I am doing wrong here?

Thank you!

**Comment by Erhannis** [comment]
ZeroConnect caches old scans by default, so I believe you're just getting the old scan result.  I've just added a `clearOldScans` function, try that and see if it fixes your problem.

**Comment by ot-repo** [comment]
Thank you very much, it worked like a charm.

And thank you again for the great plugin!!!

**Comment by Erhannis** [comment]
Thanks; hope it helps!
