### ISSUE TITLE
Suggested README update

### ISSUE THREAD

**Issue by Morssel** [Erhannis/flutter_zeroconnect#3]
Might I suggest to mention in the ReadMe something along the lines of:

Suggested README change:
```
The value for "YOURSERVICEID" must be between 1-15 chars.
The regex in MethodChannelNsdPlatform only allows only 1 to 15 characters between the underscore (_) and the period (.).
Also the value you choose for "YOURSERVICEID" must only contain (a-z A-Z 0-9) that is alphabetical chars lower or uppercase and 0-9, no special chars or anything fancy like that.
```

Reason for change:

I just spent a fair amount of time trying to figure out why I was getting:

```
E/flutter (32229): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NsdError (message: "Service type must be in format _<Service>._<Proto>: _MT_TEST._tcp", cause: illegalArgument)
```

It ended up being that the ServiceID I had arbitrarily chosen was 17 chars, 2 chars over the hidden limit.

**Comment by Morssel** [comment]
Also it was a bit unclear on how the info.plist should be used. Likely because of my inexperience with tcp permissions in iOS but it might help to clear it up.

Suggested README change:
Add the following permissions to your Info.plist:
Note: Remember to replace `YOURSERVICEID` with your own following the rules about creating YOURSERVICEID found in this README.

```
<key>NSLocalNetworkUsageDescription</key>
<string>Required to discover local network devices</string>
<key>NSBonjourServices</key>
<array>
    <string>_YOURSERVICEID._tcp</string>
</array>
```

Reason for change:

I was confused on what the original `replace service type with your own` meant, and `_http.tcp` didn't look like a placeholder value but instead an important declaration.

Thank you for your work on this neat repo @Erhannis

**Comment by Erhannis** [comment]
Hi!  Sorry; I just figured out how to see a list of issues raised on any of my repos.
I've added a YOURSERVICEID section to the Readme - would that have been sufficient to save you the trouble, in your case?
Re: info.plist, it looks like I already made an associated correction at some point after you opened this issue (which I don't think I saw, sorry).
Are these changes sufficient, do you suppose?

**Comment by Morssel** [comment]
Yes those changes look great to me, hopefully will help the next person! 

Very thankful for your work putting this repo out there!

I am putting together a little utility app for my DnD DMing and this was just the thing I needed.
