### ISSUE TITLE
NsdError (message: "missing required configuration

### ISSUE THREAD

**Issue by ameetaujla** [Erhannis/flutter_zeroconnect#4]
Hello bro 

thanks for this plugin it works great on android and on ios emulator 
but not working on real ios device ipad or iphone 
it shows an error 
Unhandled Exception: NsdError (message: "missing required configuration", cause: internalError)

I have also added 
<key>NSLocalNetworkUsageDescription</key>
<string>Required to discover local network devices</string>
<key>NSBonjourServices</key>
<array>
    <string>_http._tcp</string>
</array>

to my info file but nothing works.. 

please help

Thanks

**Comment by Erhannis** [comment]
I haven't tested on iOS, sorry - it looks like the error is coming from NSD?  https://github.com/sebastianhaberey/nsd  You could check their docs and see if they say anything there, if you haven't already.  I'm gonna be busy for a week or two, so I probably won't investigate soon, but let me know if you figure it out or not.

**Comment by ameetaujla** [comment]
Thanks, bro, but I am unable to find a solution for it. it looks like some permission error here. because it works well on IOS emulator the only problem is when we run it on a real device. 

i am waiting for your solution. 

Thanks,

**Comment by Erhannis** [comment]
I maaaaybe found some info on the problem; I made a comment on your post in the NSD repo: https://github.com/sebastianhaberey/nsd/issues/47

**Comment by Erhannis** [comment]
Just realized this was still open - the problem has been resolved in the linked issue.
